[general]
import = [
    "~/.config/alacritty/themes/themes/compline.toml"
]

[font]
size = 7.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000

[window]
opacity = 1.0

[window.padding]
x = 2
y = 2